### ISSUE TITLE
Limit unneeded permissions on Android

### ISSUE THREAD

**Issue by andreipfeiffer** [tim-js/tito-registration#2]
Search for permissions here:
https://docs.expo.io/versions/latest/workflow/configuration/

**Comment by ovidiubite** [comment]
done. Only 12 permissions required now

**Comment by andreipfeiffer** [comment]
How many were before?

**Comment by ovidiubite** [comment]
36 I think

**Comment by ovidiubite** [comment]
yep. 

36 total (24 differentiating + 12 common) 

And now we have only the common ones :D
