### ISSUE TITLE
Add a Close button during/after scan

### ISSUE THREAD

**Issue by andreipfeiffer** [tim-js/tito-registration#4]
Dupa ce scanezi, nu ai buton de Close. Daca scanezi, checkin, scan again acelasi, already checkedin ... butonul back de pe Android nu mai functioneaza chiar cum trebuie, iar pe iOS nu ai back.

Ar trebui sa ai un buton sa poti sa inchizi si in timpul scanarii, si dupa.

**Comment by ovidiubite** [comment]
done
